import { Pool } from "pg";
import { NextResponse } from "next/server";
import { assertLocalRequest } from "../../../../../server/access";

export const dynamic = "force-dynamic";

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try { assertLocalRequest(request.headers); } catch { return NextResponse.json({ error: "unauthorized" }, { status: 401 }); }
  const { id } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(id) || !process.env.DATABASE_URL) return NextResponse.json({ error: "brief_not_found" }, { status: 404 });
  const pool = new Pool({ connectionString: process.env.DATABASE_URL, connectionTimeoutMillis: 5000 });
  try {
    const result = await pool.query(`SELECT b.id,b.investigation_id,b.cohort_id,b.title,b.status,b.current_version,b.created_at::text,b.updated_at::text,v.content,v.markdown_export
      FROM brief b JOIN brief_version v ON v.brief_id=b.id AND v.version_number=b.current_version WHERE b.id=$1`, [id]);
    const row = result.rows[0];
    if (!row || row.content?.dataMode !== "live") return NextResponse.json({ error: "brief_not_found" }, { status: 404 });
    const content = row.content;
    const evidenceIds = content.supportingEvidenceIds ?? [];
    const contradicting = content.contradictingEvidenceIds ?? [];
    return NextResponse.json({ brief: { id: row.id, investigationId: row.investigation_id, title: row.title, cohortId: row.cohort_id, dataMode: content.dataMode, status: row.status, currentVersion: row.current_version, createdAt: row.created_at, updatedAt: row.updated_at, period: content.period, datasetId: content.runId, signalRunId: content.runId, methodVersion: content.methodVersion ?? "live-deterministic", author: "NADI live review", executiveSummary: content.summary, analystQuestion: content.investigationQuestions?.[0] ?? "Live signal review", scope: "Bounded live cohort", signalBreadth: "Stored cohort result", primaryDrivers: [], counterevidenceSummary: contradicting.length > 0 ? `${contradicting.length} contradicting observation(s) were flagged; inspect the citation register.` : "No counterevidence was generated by the deterministic review.", publicIndicatorContext: "not_comparable", followUpQuestions: content.investigationQuestions ?? [], analystNotes: content.limitations?.join(" ") ?? "", summary: content.summary, findings: (content.claims ?? []).map((claim: { kind: string; text: string; evidenceIds?: string[] }) => ({ kind: claim.kind, statement: claim.text, citations: claim.evidenceIds ?? [] })), claims: content.claims ?? [], evidenceRegister: evidenceIds.map((e: string) => ({ id: e })), supportingEvidenceIds: evidenceIds, contradictingEvidenceIds: contradicting, dataGaps: content.dataGaps ?? [], limitations: content.limitations ?? [], markdownExport: row.markdown_export } });
  } catch { return NextResponse.json({ error: "database_query_failed" }, { status: 503 }); }
  finally { await pool.end(); }
}
